
project_id = "zbnwztqwkusdurqllgzc"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[functions.verify-dodo-payment]
verify_jwt = true

[functions.openai-chat]
verify_jwt = false

[functions.send-enrollment-email]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.generate-blog-post]
verify_jwt = false

[functions.generate-content-summary]
verify_jwt = false

[functions.generate-seo-keywords]
verify_jwt = false
