
import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.39.3"

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders })
  }

  try {
    // Create a Supabase client with the Auth context of the logged in user
    const supabaseClient = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '',
      { auth: { persistSession: false } }
    )

    const { topic, category, wordCount = 1200 } = await req.json()

    if (!topic || !category) {
      return new Response(
        JSON.stringify({
          error: 'Missing required parameters: topic, category'
        }),
        {
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
          status: 400,
        }
      )
    }

    // Generate a unique slug for the blog post
    const slug = generateSlug(topic)

    // Check if a blog post with this slug already exists
    const { data: existingPost } = await supabaseClient
      .from('blog_articles')
      .select('slug')
      .eq('slug', slug)
      .single()

    if (existingPost) {
      return new Response(
        JSON.stringify({
          error: 'A blog post with this topic already exists'
        }),
        {
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
          status: 409,
        }
      )
    }

    // Fetch relevant keywords for the category to incorporate
    const { data: keywordsData } = await supabaseClient
      .from('seo_keywords')
      .select('keyword')
      .eq('category', category.toLowerCase())
      .order('relevance_score', { ascending: false })
      .limit(5)

    const keywords = keywordsData?.map(k => k.keyword) || []
    const keywordsText = keywords.length > 0 ? 
      `Incorporate these SEO keywords naturally: ${keywords.join(', ')}` : ''

    // Draft a table of contents for a structured article
    const tableOfContents = `
      1. Introduction
      2. Understanding ${topic}
      3. Benefits of ${topic} in tech careers
      4. How mentorship enhances learning ${topic}
      5. Building projects with ${topic}
      6. Common challenges and solutions
      7. Career opportunities with ${topic} skills
      8. Conclusion`

    // Generate blog post using AI (mock implementation - you would replace this with actual API call)
    const blogContent = `# ${topic}: A Comprehensive Guide for Tech Professionals

## Introduction

In today's rapidly evolving tech landscape, mastering ${topic} has become essential for professionals looking to advance their careers and build impactful projects. This guide explores how dedicated mentorship can accelerate your journey to becoming proficient in ${topic}.

## Understanding ${topic}

${topic} represents a critical area of technology that continues to grow in demand. As companies increasingly rely on technical solutions for their operations, professionals skilled in ${topic} are positioned to make significant contributions and advance their careers.

${tableOfContents}

... (remainder of content would be generated by AI)

## Conclusion

Mastering ${topic} is a journey that combines theoretical knowledge with practical application. With the guidance of experienced mentors, you can navigate this path more efficiently, building real-world projects that demonstrate your skills to potential employers.

Our platform connects you with mentors who have industry experience in ${topic}, ensuring you receive personalized guidance tailored to your career goals and learning style. Start your journey today and transform your career with expert-guided project development.`

    // Generate meta description
    const metaDescription = `Learn ${topic} with personalized mentor guidance. Build portfolio-ready projects and advance your tech career with expert support.`

    // Create SEO-friendly title
    const title = `${topic}: Building Real-World Projects with Expert Mentor Guidance`

    // Create social media optimized title and description
    const socialTitle = `Master ${topic} Through Guided Project Building`
    const socialDescription = `Skip the endless tutorials and build real projects in ${topic} with 1-on-1 mentorship from industry professionals.`

    // Insert the blog post into the database
    const { data, error } = await supabaseClient
      .from('blog_articles')
      .insert({
        title,
        slug,
        meta_description: metaDescription,
        content: blogContent,
        category,
        tags: [category, 'Mentorship', 'Career Growth', 'Project-Based Learning'],
        reading_time_minutes: Math.ceil(wordCount / 200), // Estimate reading time
        seo_keywords: keywords,
        social_title: socialTitle,
        social_description: socialDescription,
        published: true,
        published_at: new Date().toISOString()
      })
      .select()

    if (error) throw error

    return new Response(
      JSON.stringify({
        success: true,
        message: 'Blog post generated successfully',
        post: data?.[0]
      }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 201,
      }
    )
  } catch (error) {
    console.error('Error generating blog post:', error)
    return new Response(
      JSON.stringify({ error: error.message }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 500,
      }
    )
  }
})

/**
 * Generate a URL-friendly slug from a title
 */
function generateSlug(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^\w\s-]/g, '') // Remove special characters
    .replace(/\s+/g, '-') // Replace spaces with hyphens
    .replace(/-+/g, '-') // Replace multiple hyphens with a single hyphen
}
